### PR TITLE
add local language basemaps (but not all)

### PR DESCRIPTION
**Pull request by pmacMaps**
Add some local language basemaps.  Maybe this (partially) resolves [esri-leaflet-issue-1139](https://github.com/Esri/esri-leaflet/issues/1139)?

### CODE REVIEW

**Comment by jgravois** [comment]
given the [caveats](https://github.com/Esri/esri-leaflet-vector#disclaimer) associated with this plugin, i'm hesitant to add even more basemaps to it.

that said, i _would_ welcome a PR in the documentation page that shows how to load a local language vector basemap using its item id.

**Comment by pmacMaps** [comment]
That sounds like a good idea.  Thanks for the feedback.

**Comment by pmacMaps** [comment]
@jgravois, feel free to close this PR, as we dealt with it in the documentation site.

**Comment by jgravois** [comment]
thanks @pmacMaps. i appreciate your contributions!

**Pull request closed without merging**
