### PR TITLE
Issue #158

### PR DESCRIPTION
**Pull request by sdthaker**
## Changes Made:
* Added error handling within `src/VectorTileLayer.js` when api key or token is not provided. 
* Updated all test cases within `spec/VectorTileLayerSpec.js` to pass api key or token so that test cases can pass, as discussed [here](https://github.com/Esri/esri-leaflet-vector/issues/158#issuecomment-1751183904).

## Testing
* Automated testing of the code changes using `npm test`, passed all tests,
image
* Manual testing of the HTML files within `/examples` by opening them onto the browser, to make sure the error is shown to the user on the console, as discussed [here](https://github.com/Esri/esri-leaflet-vector/issues/158#issuecomment-1750943271).

## Issue
* Fixes issue #158 

## Additional Notes
Please let me know if there are any other changes that are to be made as part of the PR. I might've missed something considering I'm quite new to this repo and open-source development in general. Thanks!

### CODE REVIEW

**Review by patrickarlt — CHANGES_REQUESTED** [review]
@sdthaker thanks for opening this up. Unfortunately the issue didn't have a lot of good information about the proper resolution of the issue. The main missing detail is that `apiKey`/`token` is an optional parameter and not all services will require it.

If you want to take a stab at this then the proper way to resolve this would be to check for an error message if a request with an `apiKey`/`token` fails and then we could prompt the user that their provided `apiKey`/`token` property might be invalid or missing.

**Comment by sdthaker** [comment]
So should I revert back the code that I changed for all the test cases in `spec/VectorTileLayerSpec.js`? Thanks

**Comment by patrickarlt** [comment]
@sdthaker I would probably start by reverting all changes you have made so far (sorry) and adding a check on these lines https://github.com/Esri/esri-leaflet-vector/blob/master/src/VectorTileLayer.js#L62-L67 when there is an error loading the style add the error messages there. You'll need to test lots of different scenarios with an invalid token (just any random string) to make sure you catch all the different error messages since each of these scenarios will produce different error messages:

* Loading from an item id
* Loading from a service URL
* Loading from a `style` obejct
* Loading from an enumerated basemap with L.Esri.VectorBasemapLayer
* Loading from an item id with L.Esri.VectorBasemapLayer

**Comment by sdthaker** [comment]
After adding a console.log for the error variable, above line 62, building the static files and opening each of them on the browser console, I always see the error being printed as either undefined or null. Am I testing this right?

**Comment by sdthaker** [comment]
I've added a `console.log()` to show the error to the user. I tested the first 3 bullet points, by manually editing `examples/custom-vtl-dev.html` script tag and it logged the error. I was unsure about how to test the last 2 bullet points. Please let me know if the commit I made makes sense and if there is anything else to be added/removed as part of this PR also please let me know.

I apologize, I'm quite new to this project so everything is hatwire for me right now, still trying to make sense of what's the purpose of this project, what the classes in the src directory do, how everything is connected etc, etc. @patrickarlt

**Comment by sdthaker** [comment]
Hi, please provide an update on this PR, whether it needs anything else to be added or if it's good to be merged! Thanks!

**Pull request closed without merging**
